name: Develop Testing Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  test:
    name: Test Contract Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup dependencies
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: 'yarn'
          cache-dependency-path: './yarn.lock'
      - name: Install Git
        run: sudo apt install git -y
      - name: Install modules
        run: yarn install
      - name: Compile contracts
        run: yarn compile
      - name: Test the contracts
        run: yarn test

